version: '3.0'
services:
  zookeeper:
    image: zookeeper:3.4.14
    hostname: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
      - "2888"
      - "3888"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: zookeeper-1:2888:3888

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - "KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://:9094"
      - "KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
